#!/bin/bash
# Version 5

packageExt="zip"
packageName="redditwallpaper"
packageVersion="$1"
if [ -z "$1" ]
then
  echo "missing version argument"
  exit 1
fi
rm ${packageName}-v*.${packageExt}
cd package || exit 1
filename=${packageName}-v${packageVersion}.${packageExt}
zip -r $filename *
mv $filename ../$filename
cd ..
echo "md5: $(md5sum $filename | awk '{ print $1 }')"
echo "sha256: $(sha256sum $filename | awk '{ print $1 }')"
