#!/bin/bash
# Version 2

packageNamespace="io.github.bayang.redditwallpaper"
packageServiceType="Plasma/Wallpaper"
restartPlasmashell=false

for arg in "$@"; do
	case "$arg" in
		-r) restartPlasmashell=true;;
		--restart) restartPlasmashell=true;;
		*) ;;
	esac
done

isAlreadyInstalled=false
kpackagetool6 --type="${packageServiceType}" --show="$packageNamespace" &> /dev/null
if [ $? == 0 ]; then
	isAlreadyInstalled=true
fi

if $isAlreadyInstalled; then
	# Eg: kpackagetool6 -t "Plasma/Applet" -u package
	kpackagetool6 -t "${packageServiceType}" -u package
	restartPlasmashell=true
else
	# Eg: kpackagetool6 -t "Plasma/Applet" -i package
	kpackagetool6 -t "${packageServiceType}" -i package
fi

if $restartPlasmashell; then
	killall plasmashell
	kstart plasmashell
fi
